### PR TITLE
[14.0][FIX] sale_commission_partial_settlement: handle settlement deletion

### PR DESCRIPTION
**Pull request by HekkiMelody**
This commit fixes an issue where, if a settlement was deleted or canceled, any partial commission would not be recreated because it was still considered paid.

Includes a small refactor of the files and deletion of some unused fields.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@Daniel-Melian @dalonsofl FYI

**Comment by HekkiMelody** [comment]
Also added migration scripts

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

To merge with nobump

**Comment by HekkiMelody** [comment]
Added a new field "is_fully_settled"

**Review by renda-dev — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
