### PR TITLE
[16.0][MIG] sale_commission_product_criteria_domain

### PR DESCRIPTION
**Pull request by SirAionTech**
Migration from `14.0` (https://github.com/OCA/commission/tree/0cb07b1fe6e6a07db5f5a9a823d5e593b8be26c2/sale_commission_product_criteria_domain).

I have included a couple of **FIX**es that I have noticed while looking at the module code, I'll backport them when this is merged.

I had to change the demo data because of conflicts with other modules, I added more details in the **[MIG]** commit description.

Depends on:

- [x] https://github.com/OCA/commission/pull/466
      This one is not a dependency of the module itself, but I have noticed that tests fail if the **_discount** module is missing.
      And it looks like adding this in **test-requirements.txt** is not enough because the **_discount** module is not tested.
      After deeper investigation, what happens is that the agent line of the order line matches the commission_type `sale_commission_product_criteria_discount.demo_commission_rules_item_disc_2`, resulting in the tests failure:
      
     > Traceback (most recent call last):
     File "/path/to/commission/sale_commission_product_criteria_domain/tests/test_sale_commission_product_cri>teria_domain.py", line 258, in test_commission_domain
          self.assertEqual(so.order_line.agent_ids.amount, 15)
       AssertionError: 10.0 != 15

     because the fixed_discount of the matched commission item is 15 but if the module **sale_commission_product_criteria_discount** is not installed, another commission item is matched (`sale_commission_product_criteria.demo_commission_rules_item_1`) that has fixed_discount 10.

     **TL;DR**: test will fail until https://github.com/OCA/commission/pull/466 is merged, test-requirements is no use.

### CODE REVIEW

**Comment by SirAionTech** [comment]
@ilyasProgrammer, @aleuffre, @francesco-ooops you worked on this, maybe you want to have a look?

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Review by ilyasProgrammer — APPROVED** [review]
LGTM

**Comment by SirAionTech** [comment]
Rebased after https://github.com/OCA/commission/pull/465#event-11846298602

**Comment by francesco-ooops** [comment]
@ilyasProgrammer good for merge? if so, you can launch command

**Comment by ilyasProgrammer** [comment]
@pedrobaeza Need your help to merge

**Comment by francesco-ooops** [comment]
@SirAionTech it's not working according to https://github.com/OCA/commission/pull/465#issuecomment-1951971007

**Comment by francesco-ooops** [comment]
@SirAionTech would you mind backporting the missing commits to v14? thanks!

**Comment by SirAionTech** [comment]
> @SirAionTech it's not working according to [#465 (comment)](https://github.com/OCA/commission/pull/465#issuecomment-1951971007)

You can open an issue in https://github.com/OCA/oca-github-bot.

**Pull request merged**
