### PR TITLE
[14.0][FIX] sale_commission_product_criteria_domain: not agent anymore - cl…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…ear realtions.

Small fix - unlink related commission.item.agent records when partner is not agent anymore.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you rebase?

**Review by renda-dev — APPROVED** [review]
Code review, LGTM.

Please, fix commit message before merging.

**Comment by ilyasProgrammer** [comment]
> Code review, LGTM.
> 
> Please, fix commit message before merging.

Whats wrong with the message ?

**Comment by francesco-ooops** [comment]
> > Code review, LGTM.
> > Please, fix commit message before merging.
> 
> Whats wrong with the message ?

Shorten it to make it fit the commit name

Additional comments can go to commit description

**Pull request merged**
