### PR TITLE
[15.0][IMP] account_commission: Improve settlement report

### PR DESCRIPTION
**Pull request by pedrobaeza**
Switch invoice line column to Invoice name + Customer + Description + Amount for better comprehension.

@Tecnativa TT46914

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by jguenat — COMMENTED** [review]
price_subtotal might not be relevant depending on how the commission is calculated but I agree it is useful for gross amount based commission, which is the generic case.

Could add a condition on the price_subtotal column but hard to do because there can be multiple commissions types.

what do you think?

**Comment by pedrobaeza** [comment]
It wouldn't be performant-wise to explore all the commission lines to see if there's any commission of such type. But the same problem is for quantity that you previously added: for my customers, it's not useful, but as it takes very few, let's add both and it can be ignored if not needed.

**Review by jguenat — APPROVED** [review]
Okay let's merge like that. Specific needs can be addressed in client specific custo

**Comment by pedrobaeza** [comment]
Thanks for your comprehension.

/ocabot merge minor

**Pull request merged**
