### PR TITLE
[14.0][FIX] sale_commission: Regenerate agents button invisibility

### PR DESCRIPTION
**Pull request by jguenat**
- xml states and attrs invisible are combined with AND operator which was not correct in this case, we need OR.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you review?

**Review by ilyasProgrammer — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@pedrobaeza go?

**Comment by pedrobaeza** [comment]
/ocabot merge minor

Please fw-port it to upper versions if applicable

**Comment by jguenat** [comment]
> /ocabot merge minor
> 
> Please fw-port it to upper versions if applicable

Already did it in #410 and #411 :)
maybe @ilyasProgrammer can review those too? thx

**Pull request merged**
