### PR TITLE
[14.0] [FIX] sale_commission_partial_settlement: reset agent partial

### PR DESCRIPTION
**Pull request by renda-dev**
Set the invoice line of the agent as not settled if it does not have any settlement linked to it.

Also, proposing me and my team as maintainers of this module.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

This PR allows recalculation of settlements for invoices for which settlements had previously been created and deleted (before agent invoice creation)

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza can I ask you to merge this one? Thanks!

**Comment by pedrobaeza** [comment]
Merging blindly:

/ocabot merge nobump

**Comment by francesco-ooops** [comment]
Appreciate it!

**Pull request merged**
