### PR TITLE
These changes are in response to #333 comment: add readme

### PR DESCRIPTION
**Pull request by kluna1998**
Add readme's CONFIGURE section.

In response of the comment   https://github.com/OCA/commission/issues/333#issuecomment-1276162972 made by @francesco-ooops.

### CODE REVIEW

**Review by francesco-ooops — COMMENTED** [review]
@kluna1998 thanks, much clearer now!

although I think you only need to add CONFIGURE.rst file in this PR

**Comment by kluna1998** [comment]
Well, I just did oca-gen-addon-readme, which it was already not needed, but I wanted to check the final resutl :smile:

**Review by sanchonuria — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers is it good like this?

**Review by hildickethan — APPROVED** [review]

**Pull request merged**
