### PR TITLE
[IMP] sale_commission_agent_restrict: do not populate customers agents

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
Replacement for https://github.com/OCA/commission/pull/369

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@ilyasProgrammer ok you can rebase

**Review by francesco-ooops — APPROVED** [review]
functional ok!

@rousseldenis @simahawk could you take a look? thanks!

**Review by simahawk — APPROVED** [review]
LG, just code review

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers could this be merged?

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers gentle reminder :)

**Comment by francesco-ooops** [comment]
@pedrobaeza what do you think?

**Comment by pedrobaeza** [comment]
Merging based on existing reviews

/ocabot merge nobump

**Pull request merged**
