### PR TITLE
[13.0][IMP] sale_commission: Add optional in commission_status field related to order view

### PR DESCRIPTION
**Pull request by victoralmau**
Add optional in `commission_status` field related to order view

Please @joao-p-marques and @sergio-teruel can you review it?.

@Tecnativa TT28323

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can buttons be hidden as well?

**Comment by victoralmau** [comment]
Is not possible to apply "_optional_" to buttons.
IMO maybe it's a good idea to show buttons only to "Sale Admin" group users.
What do you think about it?

**Comment by pedrobaeza** [comment]
Well, it's a big functional change. Till now, any salesman can modify the agents (but not the amounts). And anyway, they can't see the detail, so in any case, the button must be there (maybe hidden), but the popup to be editable or not.

**Comment by victoralmau** [comment]
Ping @joao-p-marques and @sergio-teruel

**Review by sergio-teruel — APPROVED** [review]

**Review by joao-p-marques — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
