### PR TITLE
[16.0][FIX] sale_commission_product_criteria

### PR DESCRIPTION
**Pull request by toita86**
Fw port of https://github.com/OCA/commission/pull/568

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Review by jbernausVunkers — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@pedrobaeza merge?

**Comment by pedrobaeza** [comment]
I don't know about this module. As there's a maintainer, he can merge it.

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you merge please?

**Pull request merged**
