### PR TITLE
[17.0][MIG] commission: Migration to 17.0

### PR DESCRIPTION
**Pull request by ambientWave**
I upgraded the three main modules, which have the following technical names:
'commission', 'sale_commission', 'account_commission'
to be installed on Odoo 17.0.
The demo files weren't upgraded and hence, an error during installation is warning user that demo data wasn't populated. However, all modules can be used without demo data.
All contributions and comments are welcomed.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0. And you should do one module per PR.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by ambientWave** [comment]
@pedrobaeza If I am considering to re-run the steps as provided in the technical guide you provided, should I make different repository for each module?

**Comment by pedrobaeza** [comment]
One branch per module.

**Comment by ambientWave** [comment]
@pedrobaeza would you endorse deleting my repository and restart a clean one with same name or what should I do if I intend to push the migrated repository that I crafted by following the steps?
Almost forgot to thank you for your quick replies

**Comment by pedrobaeza** [comment]
I can't do that things, as it's your repository. You just need to create as many branches as you need.  https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Pull request closed without merging**
