### PR TITLE
Ádded translations (es)

### PR DESCRIPTION
**Pull request by EdgarSolorzano**
Corrected and added some translations in spanish.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use Transifex instead: https://odoo-community.org/page/translate

**Comment by EdgarSolorzano** [comment]
Hi Pedro, is it possible to fix the "Settlments" (wrong spelled) menu item and the missing Commissions Management keyword through Transifex?

**Comment by pedrobaeza** [comment]
OK, I reopen the PR for only the misspelled word, but no need to refresh POT file (it should be removed in fact).

**Comment by pedrobaeza** [comment]
No answer, so I close.

**Pull request closed without merging**
