### PR TITLE
[16.0][IMP]account_commission: add test of reversed moves + docs

### PR DESCRIPTION
**Pull request by Tisho99**
FW PORT of #503

### CODE REVIEW

**Comment by Tisho99** [comment]
@pedrobaeza 
The FW PORT of https://github.com/OCA/commission/pull/503 is ready

**Review by pedrobaeza — COMMENTED** [review]
Does this mean that 16.0 already handles this correctly? If so, please change the commit message indicating that this is only an improvement on documentation + test, instead of a fix.

**Review by chienandalu — CHANGES_REQUESTED** [review]
Apply https://github.com/OCA/commission/pull/511 and https://github.com/OCA/commission/pull/506 changes for more reliable tests

**Comment by pedrobaeza** [comment]
@chienandalu I think it's better that you fw-port directly that PRs.

**Comment by chienandalu** [comment]
> @chienandalu I think it's better that you fw-port directly that PRs.

But they depend on this one :sweat_smile:

**Comment by pedrobaeza** [comment]
Ah, OK. @Tisho99 all yours :wink:

**Review by chienandalu — APPROVED** [review]

**Comment by Tisho99** [comment]
@pedrobaeza @chienandalu 

Applied #511 and #506

Thanks for the fixes!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
