### PR TITLE
[IMP] sale_commission: move check of the amount to the end

### PR DESCRIPTION
**Pull request by etobella**
The check has been moved to the end in order to perform the join of a negative settlement and a positive settlement if possible.

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please make an iterative check for breaking when the first exception is found instead of needing to compute whole set before raising the exception. A test with the user case (positive and negative) would be very advisable also

**Comment by etobella** [comment]
You should wait to the end. Let's assume that an agent has two settlements, the first negative and the second positive and the total is positive. If we fail on the first iteration, it will fail, but with the current code it will wait until the end and check it later. If we want to check it inside the loop, we should sort the data by total.
Also, it cannot be checked here, as the module will create an invoice for each settlement. A second module is necessary in order to show it.

**Comment by pedrobaeza** [comment]
I think you haven't understood me. I'm talking about:

1. Make a `for` loop instead of `mapped` + `filtered`.
2. Add unit tests.

**Comment by etobella** [comment]
Ok! Sorry for the misunderstanding :wink:

**Comment by etobella** [comment]
@pedrobaeza your comments have been attended.

**Review by pedrobaeza — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Tested on runbot. Tech review

**Pull request merged**
