### PR TITLE
change compute period for agent settle

### PR DESCRIPTION
**Pull request by scigghia**
in this way, date range for settle is correct

### CODE REVIEW

**Comment by giudalo** [comment]
:+1:

**Comment by Daniel-CA** [comment]
This change is not necessary, the settlement wizard is set to create all settlements until the date defined.
So if your settlements are created monthly if you check last day of the current month is not going to be settled.

**Comment by pedrobaeza** [comment]
You have to put it at least the first day of the next period.

**Comment by scigghia** [comment]
So user have no choice, even if it want to settle only a week for a specific agent. 
is possible that i want to pay in advance one week for a monthly agent or two moth for a quarterly agent .
My opinion is to give freedom to user.

**Comment by pedrobaeza** [comment]
Not this way. That's a change in the behavior. You can add the feature (adding the corresponding selection to be made by the user), but not replacing the current one.

**Pull request closed without merging**
