### PR TITLE
[14.0][ADD] sale_quick_commission

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
This module makes **sale_commission** and **sale_quick** compatible.

### CODE REVIEW

**Comment by ilyasProgrammer** [comment]
@pedrobaeza Hi. Is it correct repo for this module ?

**Comment by pedrobaeza** [comment]
Yeah, I think it's OK, being transversal for all the commission thing as due to the others being very crowded.

**Comment by francesco-ooops** [comment]
@pedrobaeza can you help us out with precommit?

**Comment by pedrobaeza** [comment]
You have to update the copier template in the repository.

**Comment by ilyasProgrammer** [comment]
> You have to update the copier template in the repository.

@pedrobaeza how to do it ?

**Comment by pedrobaeza** [comment]
`copier -f update` in the main repository folder having copier installed.

**Review by francesco-ooops — APPROVED** [review]
functional ok!

@pedrobaeza good?

**Comment by pedrobaeza** [comment]
There's only one review.

**Comment by francesco-ooops** [comment]
> There's only one review.

yes I wanted yours haha

**Comment by pedrobaeza** [comment]
I'm not a user of `sale_quick`, so I can't review.

**Comment by francesco-ooops** [comment]
@damdam-s as sale_quick creator, could you take a look? thanks!

**Review by SicurSam — APPROVED** [review]
functional ok!

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you make a specific PR with the code for copier and remove it from here?

**Comment by ilyasProgrammer** [comment]
https://github.com/OCA/commission/pull/383

**Comment by francesco-ooops** [comment]
@ilyasProgrammer ok you can rebase

**Comment by francesco-ooops** [comment]
@pedrobaeza good for merge?

**Pull request merged**
