### PR TITLE
[IMP] sale_commission: Allow to group invoices

### PR DESCRIPTION
**Pull request by etobella**
With 13.0 version, it was lost the option to merge all the settlements of a partner and company to a single invoice. With this change, you can select the behavior that you will use

### CODE REVIEW

**Comment by pedrobaeza** [comment]
More than "merge invoices", it's to generate grouped settlements invoices...

Where this option was in 12.0?

**Comment by etobella** [comment]
You are right about the name.

There was not an option for that, however, a hook existed that allowed to make the change:

https://github.com/OCA/commission/blob/12.0/sale_commission/models/settlement.py#L136

This PR has copied the logic from odoo `sale` module.

**Comment by pedrobaeza** [comment]
2 comments:

- Check the recent bug we discovered on sale invoicing: https://github.com/odoo/odoo/pull/71686
- Maybe you can split again the logic of header/lines (passing `Form` as argument), for improving both the readability and the extensibility.

**Comment by etobella** [comment]
Thanks for the fix @pedrobaeza 
I would prefer to not use the Form as it should be slower than this method

**Comment by pedrobaeza** [comment]
> I would prefer to not use the Form as it should be slower than this method

That's not true, as now, if you have N invoices, N Forms are instantiated and N lines, and then converted to vals, and then process the vals. With my proposal, only 1 Form will be instantiated and N lines, so it's worth to do it.

**Comment by etobella** [comment]
True, I didn't notice that. I will check, thanks!!!

**Comment by etobella** [comment]
@pedrobaeza Comments attended, WDYT?

**Review by pedrobaeza — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
Pleas forward-port it to v14

**Pull request merged**
