### PR TITLE
[MIG] sale_commission_agent_restrict: Migration to 16.0

### PR DESCRIPTION
**Pull request by SirAionTech**
Migration from `14.0` (https://github.com/OCA/commission/tree/6c7c904711397dc93d06801d93533839194904a7/sale_commission_agent_restrict).

Depends on:
- [x] https://github.com/OCA/server-ux/pull/859

### CODE REVIEW

**Comment by SirAionTech** [comment]
@aleuffre would you like to have a look since you are the module's maintainer?
Also @ilyasProgrammer and @francesco-ooops might be interested since you worked on this

**Review by francesco-ooops — APPROVED** [review]
Functional LGTM!

@ilyasProgrammer can you check code?

**Review by ilyasProgrammer — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza can this be merged? thanks!

**Pull request merged**
