### PR TITLE
[IMP] it was added sale_commission_salesman from v14

### PR DESCRIPTION
**Pull request by JavierVescio**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This must respect commit history and rename it to `commission_salesman`.

**Comment by JavierVescio** [comment]
> This must respect commit history and rename it to `commission_salesman`.

Sorry, this is the first time I'm doing this. What do you mean by respecting commit history? What am I doing wrong? Thank you.

**Comment by pedrobaeza** [comment]
Follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 procedure, and then, rename the module.

**Comment by pedrobaeza** [comment]
Already migrated: https://github.com/OCA/commission/tree/15.0/commission_salesman

**Comment by pedrobaeza** [comment]
We will repeat with the correct name, but this one should be closed.

**Pull request closed without merging**
