### PR TITLE
15.0 mig sale commission pricelist

### PR DESCRIPTION
**Pull request by slominchar**

### CODE REVIEW

**Comment by patel1008b** [comment]
@slominchar Thanks for your efforts to make it available for version 15. Is it ready for test on client's system ?

**Comment by patel1008b** [comment]
@rousseldenis is there any chance to merge this PR ?

**Comment by rousseldenis** [comment]
> @rousseldenis is there any chance to merge this PR ?

@bhaveshselarka You should ping first @slominchar as this PR is red.

**Comment by rousseldenis** [comment]
@slominchar Could you edit your PR description in order to point to the PR that is migrating sale_commission module ? Thanks

**Pull request closed without merging**
