### PR TITLE
[IMP] [8.0] sale_commission: Add settlement menu view for sale_manager

### PR DESCRIPTION
**Pull request by Daniel-CA**

### CODE REVIEW

**Comment by Daniel-CA** [comment]
I was thinking to add a wizard to merge all settlements for a same agent and period in one so it can be invoiced all lines together (I know that it can be done using invoice_merge later on) but this is a cleaner way.

**Comment by pedrobaeza** [comment]
You must do only one settlement per period. If not, remove the previous settlements. Any way, this mustn't be done here.

**Comment by Daniel-CA** [comment]
Sorry, I posted before finishing the post.
The main problem is currently a new settlement is created for every ```account.invoice.line.agent```

**Comment by pedrobaeza** [comment]
Do you mean for each different agent? That's the expected result.

**Comment by Daniel-CA** [comment]
No, it happens for the same agent too.

**Comment by pedrobaeza** [comment]
Well, that's not what happens normally. This is a bug then, not a feature. Please fix it instead.

**Comment by Daniel-CA** [comment]
:+1:

**Comment by Daniel-CA** [comment]
@pedrobaeza I just want to know why this improvement is not valid. A lot of people is used to using tree views rather than reports, thanks.

**Comment by pedrobaeza** [comment]
Sorry, I mixed the concepts (but because you mixed previously the concept of the PR with the other thing about merging settlements).

**Comment by Daniel-CA** [comment]
Ok, thanks.  :satisfied:

**Comment by Daniel-CA** [comment]
Can this view improvement be merged?

**Review by agaldona — APPROVED** [review]

**Review by oihane — APPROVED** [review]
LGTM

**Review by atchuthan — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please backport it to newer versions?

**Pull request merged**
