### PR TITLE
[14.0][FIX] sale_commission_agent_restrict: do not deactivate base rules

### PR DESCRIPTION
**Pull request by HekkiMelody**
Fix that ended up involving a significant refactor of the entire module. The goal was mostly to keep the same functionality but also keep the security rule about hiding private addresses for accounts that are not agents.

The commit adds a new OCA dependency; there's some code cleanup and refactoring.

~~NOTE: the PR is not ready, I'm opening it early to allow people to do code reviews and functional tests.~~

TODO:  
- [x]  add tests
- [x] migration from current version of the module to new version

The PR is now ready for review

### CODE REVIEW

**Review by ilyasProgrammer — APPROVED** [review]
lgtm

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Comment by francesco-ooops** [comment]
@pedrobaeza shall we proceed? ready with migration and tests in an effort to increase compatibility

**Comment by pedrobaeza** [comment]
Wow, you were doing something very nasty... OK to guide this to more compatible things:

/ocabot merge nobump

**Pull request merged**
