### PR TITLE
[17.0] [MIG] hr_commission: Migration to 17.0

### PR DESCRIPTION
**Pull request by ambientWave**
Standard migration from version 16.0 to 17.0

All contributions and comments are welcomed.

Depends on

- https://github.com/OCA/commission/pull/497
- https://github.com/OCA/commission/pull/524

### CODE REVIEW

**Comment by ambientWave** [comment]
Dear @pedrobaeza

All checks are passed

**Comment by pedrobaeza** [comment]
Great, this should follow then the review process

https://odoo-community.org/resources/review
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

Unfortunately, I can't review each of the incoming PRs that appear in OCA (although I do a lot), and even so, in a normal process, 2 reviews are needed. I'm giving mine anyway as this module is simple and it's originally mine.

You can review other PRs and ask in exchange that they review yours.

**Review by pedrobaeza — APPROVED** [review]
Diff code review

**Comment by andrel-exo** [comment]
LGTM

**Review by pedrocs-exo — APPROVED** [review]
Everything seems ok

**Review by andrel-exo — APPROVED** [review]

**Pull request merged**
