### PR TITLE
[15.0][IMP] commission: multi-currency support

### PR DESCRIPTION
**Pull request by jguenat**
Supersede #405 

Improvements based on review in #405 are in a separate commit that will be fixed up later.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't we have in settlement lines both amount in company currency and in the original currency?

**Comment by jguenat** [comment]
If we need to settle the settlement with an invoice in the company currency it could be useful indeed.
We need to be careful about currency exchange rate. On the settlement line the rate from the source invoice date is used, then when we make the settlement invoice it will be another rate.
This could lead to confusion.

Maybe if we are able to choose the settlement invoice currency (original or company) then there is enough flexibility.

Next week I have a meeting with a customer that use commissions in different currency. I'll ask how they manage it actually. I guess it depends on the commission agreement.

**Comment by JordiMForgeFlow** [comment]
Hi @jguenat 

Are there any plans to continue with this PR?

**Comment by jguenat** [comment]
Hi @JordiMForgeFlow ,

I've been using this module for a client and it seems to work like this but the real commission on foreign currency will be settled early 2024 and maybe I'll have some adjustment to do then.

But if you have time to review this we can already go forward.

**Comment by JordiMForgeFlow** [comment]
Hi @jguenat 

Any chance the PR could be rebased?

**Comment by jguenat** [comment]
@JordiMForgeFlow I rebased but we can continue there #479 no problem

**Review by JordiMForgeFlow — APPROVED** [review]
Code + functional review LGTM!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
