### PR TITLE
[11.0][FIX] avoid KeyError

### PR DESCRIPTION
**Pull request by dcorio**
These lines were breaking other modules inheriting this method with sale_commission installed

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is a nonsense... `invoice_id` is a required field, so no possible to not indicate it.

**Comment by dcorio** [comment]
@pedrobaeza damn...ignore it! it's AccountInvoiceLine and not AccountInvoice...sorry for the noise

**Comment by dcorio** [comment]
@pedrobaeza after having ran a few checks I can say that:

1. invoice_id on account.invoice.line isn't mandatory
2. there are modules that first create the account.invoice.line and the account.invoice after
3. this is the only module so far that breaks the chain

If you still believe this is "nonsense" I'll try to create PR against the other repos with modules that creates account.invoice.lines records without passing invoice_id even if it's not mandatory.

**Comment by pedrobaeza** [comment]
Hi @dcorio, I have checked in odoo itself and you're right:

https://github.com/odoo/odoo/blob/64f06858362acf584e4371e3848a6305ecea6b25/addons/account/models/account_invoice.py#L1485

They have removed the required flag from the line, so your PR is correct and apologies from my initial mistake.

**Review by pedrobaeza — APPROVED** [review]

**Review by warp10 — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Cherry-picked for v12 in 410b28cbcbe1c845eb14d01e63d6b897f683a608

**Pull request merged**
