### PR TITLE
[16.0][MIG] sale_commission

### PR DESCRIPTION
**Pull request by hildickethan**
- Standard migration to 16.0 with `odoo-module-migrator` tool
- Depends on
  - https://github.com/OCA/commission/pull/394 
  - https://github.com/OCA/commission/pull/395

### CODE REVIEW

**Comment by hildickethan** [comment]
Updated migration commit with feedback from https://github.com/OCA/commission/pull/394, pending rebase with merge of https://github.com/OCA/commission/pull/395 for green tests

**Comment by hildickethan** [comment]
Rebased :green_apple:

**Review by pedrobaeza — APPROVED** [review]

**Review by yostashiro — APPROVED** [review]
LGTM. 👍 

One minor(?) thing - the module now depends on `sale` instead of `sale_management`, and therefore runboat instance does not show the sales menu unless you go to apps and install `sale_management`.  Should we switch the dependency to `sale_management`?

In fact the `sale_commission` module in 14.0 depends on `sale_management`, and in our migration to 15.0, we changed it to `sale` as we thought it was technically not necessary to depend on `sale_management`, however I think it may have been an unnecessary move.

@pedrobaeza Can you please advise?

**Comment by hildickethan** [comment]
> In fact the `sale_commission` module in 14.0 depends on `sale_management`, and in our migration to 15.0, we changed it to `sale` as we thought it was technically not necessary to depend on `sale_management`, however I think it may have been an unnecessary move.

I think this was primarily due to moving the commissions menu out of sales and into its own. To my knowledge the norm is just to depend on `sale` unless you specifically need the dependency for some inheritance

**Comment by pedrobaeza** [comment]
Yes, let's keep it with the minimum technical dependencies:

/ocabot merge nobump

**Pull request merged**
