### PR TITLE
[14.0][FIX] sale commission agent restrict fix agent ids pop

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
FIX: not need to continue loop if it was already removed. Just return.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@pedrobaeza could this be merged please? :)

**Comment by pedrobaeza** [comment]
Merging blindly due to reviews:

/ocabot merge patch

**Pull request merged**
