### PR TITLE
[MIG] sale_commission_product_criteria

### PR DESCRIPTION
**Pull request by SirAionTech**
Migration from `14.0` (https://github.com/OCA/commission/tree/0cb07b1fe6e6a07db5f5a9a823d5e593b8be26c2/sale_commission_product_criteria).

### CODE REVIEW

**Comment by SirAionTech** [comment]
@ilyasProgrammer, @aleuffre, @francesco-ooops you worked on this, maybe you want to have a look?

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM, thanks for the code cleanup

**Review by francesco-ooops — APPROVED** [review]
Functional looks ok. 

There is a behavior we had to implement in v14 but in the end we didn't, which is related to changing "type" in "commission type" from "Product criteria" to "Fixed percentage", "By sections" or "Formula":

if CT items existed for that CT, they will still appear in menu "Commission type items", even if they're not in use/visible in CT form anymore. The idea was to use https://github.com/OCA/web/tree/14.0/web_create_write_confirm to add a popup asking user to confirm that by changing CT "type" to any of those three, all lines will be deleted. 

If you'd like to add this feature, we'd help you with merge :)

**Comment by SirAionTech** [comment]
@OCA/crm-sales-marketing-maintainers can someone have a look? There are some reviews already

**Comment by SirAionTech** [comment]
Or maybe the module maintainer @ilyasProgrammer would like to merge?

**Comment by francesco-ooops** [comment]
@pedrobaeza would it be possible to merge? I don't think maintainers can merge migrations (but I may be wrong)

**Comment by SirAionTech** [comment]
> @pedrobaeza would it be possible to merge? I don't think maintainers can merge migrations (but I may be wrong)

They can: https://github.com/OCA/oca-github-bot/issues/122

**Pull request merged**
