### PR TITLE
[12.0][ADD] sale_commission_settlement_partial_invoice

### PR DESCRIPTION
**Pull request by SirTakobi**
Superseding https://github.com/OCA/commission/pull/321.

I also fixed a particular use-case (see the added test for more details).

### CODE REVIEW

**Review by eLBati — APPROVED** [review]
Thanks

**Comment by SirTakobi** [comment]
@oca/crm-sales-marketing-maintainers is it possible to merge this?
Being a Beta module, one review should be enough; otherwise please let me know if you want me to change something, thanks!

**Comment by SirTakobi** [comment]
@oca/crm-sales-marketing-maintainers can someone have a look? Thanks!

**Comment by SirTakobi** [comment]
@OCA/crm-sales-marketing-maintainers can someone have a look? Thanks!

**Review by francesco-ooops — APPROVED** [review]
functional review ok

**Comment by SirTakobi** [comment]
@OCA/crm-sales-marketing-maintainers can someone have a look? Thanks!

**Comment by SirTakobi** [comment]
@OCA/crm-sales-marketing-maintainers can someone have a look? Thanks!
Note that @OCA-git-bot has already approved :smile:

**Pull request merged**
