### PR TITLE
[17.0][MIG] commission_formula: Migration to 17.0

### PR DESCRIPTION
**Pull request by Tisho99**
Standard migration

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@luis-ron

**Review by luis-ron — APPROVED** [review]
LGTM 👍🏻

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
