### PR TITLE
[NEW] module hr_commission_payslip

### PR DESCRIPTION
**Pull request by sadamo**
New module to integrate sale_commission and hr_payroll, inserting the commission value in the payslip

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Daniel, this should be integrated in _sale_commission_hr_ module instead. Have you taken in care the refactorization done here?: https://github.com/OCA/commission/pull/14

**Comment by pedrobaeza** [comment]
Sorry, forget what I have said. I'm seeing that the module is for v7, not v8. Anyways, a renaming the same way would help in the convergence.

**Comment by mileo** [comment]
@sadamo plz

**Comment by pedrobaeza** [comment]
This hasn't been work for a long time and it has Travis red. If you still think this is useful, please reopen a new PR without conflicts.

**Pull request closed without merging**
