### PR TITLE
[ADD] adding function for merging settlements and selttment lines vie…

### PR DESCRIPTION
**Pull request by jackjack82**
…w with pivot table

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think this is needed: if you want to merge settlements, just remove split settlements and make another settlement that includes all.

**Comment by jackjack82** [comment]
Dear Pedro,
 thank you for your mail. However here below the use case:

1) I create an agent with 10% commission on invoiced amount and Quarterly
settlment
2) I have already settled the 1Q
3) I have to settle the 2Q but I have new invoices in Q1, which were
previously forgotten
4) I click on "Settle commission" and I get two settlements, one for 1Q
(with remaining additional invoices) and one for full 2Q

I still want to make a unique invoice. I think I need to merge the
settlements.

Giacomo

**Comment by jackjack82** [comment]
Closed for #172

**Comment by pedrobaeza** [comment]
Closing this in favor of #172

**Pull request closed without merging**
