### PR TITLE
[IMP][14.0] sale_commission

### PR DESCRIPTION
**Pull request by AshishHirapara**
Agent detail button will be visible even after the invoice is created

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@pedrobaeza any opinion on this?

do you think it would be safer to add a setting in config to allow this field to be displayed after invoice is issued?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This is incorrect and shouldn't be allowed, and even more, it doesn't serve, as the agents have been already transferred to the invoice

**Comment by francesco-ooops** [comment]
> 

Can you help me understand why user shouldn't be able to check commissions in SO after invoice is created?

**Comment by pedrobaeza** [comment]
They shouldn't modify them, and as said, that information is not useful, the important one is the invoice agents information.

**Comment by francesco-ooops** [comment]
@pedrobaeza ok this can be closed then, thanks

**Pull request closed without merging**
