### PR TITLE
[IMP] sale_commission: Remove required attribute in settlement field.Added to field in view form

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT27096
ping @Yajo @chienandalu

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please remove the required to `agent_type` field as well.

**Comment by sergio-teruel** [comment]
@pedrobaeza Changes done!!

**Comment by bodedra** [comment]
@sergio-teruel can you explain the issue?

**Review by pedrobaeza — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Sorry @bodedra I think that @Yajo can explains better than me...

**Review by victoralmau — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Review by yajo — COMMENTED** [review]
The code is perfect, but IMHO you need to rewrite the commit.

The commit says what you do, but doesn't say why. If you don't explain that, then in the future somebody will come (and that somebody might even be myself who discovered the bug but have some amnesia :laughing:) and revert this, because the reason is not obvious and, at first sight, the code looks "worse" than it was.

So, please just amend your commit with a meaningful message and this shall be ready to merge :blush:

**Comment by yajo** [comment]
> Sorry @bodedra I think that @Yajo can explains better than me...

I just read this. :facepalm: Let me do the amend.

**Comment by yajo** [comment]
Done. Reason: When updating a table, modules that don't have the `required=True` setting of a field in their scope issue an `ALTER TABLE` at least twice per module. This blocks the entire table.

This module was doing that, and since the `res.partner` model is so ubiquitous, this was blocking concurrent updates.

By moving the required attribute to the views, the UX is the same, but concurrent updates work fine again.

**Comment by pedrobaeza** [comment]
Please fw-port it to v13

**Comment by yajo** [comment]
Done in https://github.com/OCA/commission/pull/271

**Comment by bodedra** [comment]
> Done. Reason: When updating a table, modules that don't have the `required=True` setting of a field in their scope issue an `ALTER TABLE` at least twice per module. This blocks the entire table.
> 
> This module was doing that, and since the `res.partner` model is so ubiquitous, this was blocking concurrent updates.
> 
> By moving the required attribute to the views, the UX is the same, but concurrent updates work fine again.

Thank you @Yajo for explanation. That's what I am looking for.

**Pull request merged**
