### PR TITLE
[12.0] ADD sale_commission_settlement_partial_invoice

### PR DESCRIPTION
**Pull request by eLBati**
Allow to generate partial agent invoice from settlement

### CODE REVIEW

**Review by mrcast — COMMENTED** [review]
@eLBati : Settlement just created, are immediately set as invoiced
**STEP**
- create an invoice with an agent
- lunch "settlements commision"
- the created settlement is in state invoiced instead of state "Settled"
Schermata del 2021-09-24 18-08-29

**Comment by eLBati** [comment]
@mrcast thanks, fixed

**Review by mrcast — APPROVED** [review]
Functional test, ok!

**Comment by eLBati** [comment]
I think this could be merged as `beta`

**Pull request closed without merging**
