### PR TITLE
[FIX] sale_commission_agent_restrict:  access updates

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok

bugfixing for access errors

**Review by SicurSam — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza this is an important functional fix, could you please review and merge? Thanks!

**Comment by pedrobaeza** [comment]
As I'm not a user of the module, I just merge based on your reviews:

/ocabot merge minor

**Comment by francesco-ooops** [comment]
> As I'm not a user of the module, I just merge based on your reviews:
> 
> /ocabot merge minor

Thank you!

**Pull request merged**
