### PR TITLE
[MIG] sale_commission_formula: Migration to 15.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration
Depends on #343

### CODE REVIEW

**Review by albariera — APPROVED** [review]
LGTM 👍 But check tests!

**Comment by patel1008b** [comment]
@olgamarcocb  Thanks for your efforts to make it available for version 15. Is it ready for test on client's system ?

**Review by etobella — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Closing in favor of #377, as that one includes the renaming due to the new refactoring.

**Pull request closed without merging**
