### PR TITLE
[16.0][MIG] sale_commission_product_criteria_discount

### PR DESCRIPTION
**Pull request by SirAionTech**
Migration from `14.0` (https://github.com/OCA/commission/tree/0cb07b1fe6e6a07db5f5a9a823d5e593b8be26c2/sale_commission_product_criteria_discount).

### CODE REVIEW

**Comment by SirAionTech** [comment]
@ilyasProgrammer, @francesco-ooops you worked on this, maybe you want to have a look?

**Review by ilyasProgrammer — APPROVED** [review]
code LGTM

**Comment by SirAionTech** [comment]
Rebased after https://github.com/OCA/commission/pull/465#event-11846298602

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Comment by SirAionTech** [comment]
Rebased on `16.0`.

**Comment by SirAionTech** [comment]
Rebased on `16.0`.

**Comment by SirAionTech** [comment]
@ilyasProgrammer you are the maintainer of this module, can you merge?

**Comment by francesco-ooops** [comment]
@pedrobaeza good to go?

**Comment by pedrobaeza** [comment]
Merging blindly following current reviews:

/ocabot merge nobump

**Pull request merged**
