### PR TITLE
[10.0][ADD] website_sale_commission_lead_geo_assign

### PR DESCRIPTION
**Pull request by SimoRubi**
Let the user assign agents to leads (more specifically to field _partner_assigned_id_ defined in https://github.com/odoo/odoo/tree/10.0/addons/website_crm_partner_assign).

### CODE REVIEW

**Review by mrcast — APPROVED** [review]
Functional test ok!

**Comment by SimoRubi** [comment]
Note that Travis is failing because it fails in 10.0 too with same error: see https://travis-ci.org/OCA/commission/builds/461905301

(trying to fix that in https://github.com/OCA/commission/pull/192)

**Review by mrcast — APPROVED** [review]
Assignation upon creation tested and ok!
thanks

**Comment by SimoRubi** [comment]
Rebased after https://github.com/OCA/commission/pull/192

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers please check, thanks

**Comment by SimoRubi** [comment]
cc @agilebg

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
