### PR TITLE
[15.0][MIG] Commission : Migration to 15.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This is the migration of the "commissions" repo to 15.0 but there are important changes with respect to previous versions.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@manuelcalerosolis please split the changes for migration + new module in a separate commit from `black` one.

**Comment by manuelcalerosolis** [comment]
I don't quite understand what you mean, create a new commit from scratch or simply change the text "[IMP] commission: black, isort"?

**Comment by pedrobaeza** [comment]
You have done both things (pre-commit stuff) and the module refactoring in the same commit.

I also miss here the `sale_commission` remaining stuff.

**Comment by manuelcalerosolis** [comment]
My intention is to continue with the refactoring as soon as possible.

**Comment by patel1008b** [comment]
@manuelcalerosolis Thanks for your efforts to make it available for version 15.  Is it ready for test on client's system ?

**Comment by BT-aestebanez** [comment]
@manuelcalerosolis Is there anything I can do to help?

**Comment by manuelcalerosolis** [comment]
> @manuelcalerosolis Thanks for your efforts to make it available for version 15. Is it ready for test on client's system ?

Yes sure, you can try it.

**Comment by manuelcalerosolis** [comment]
> @manuelcalerosolis Is there anything I can do to help?

Well it really seems that there is a problem with the commits but I don't really know how to fix it.

**Comment by BT-aestebanez** [comment]
> > @manuelcalerosolis Is there anything I can do to help?
> 
> Well it really seems that there is a problem with the commits but I don't really know how to fix it.

Normally commits black, isort looks like this:
https://github.com/OCA/account-financial-tools/pull/1404/commits/fd180d97485497cb27235dda6c9527c6d46eb141
However, yours
https://github.com/OCA/commission/pull/343/commits/5fb8108b80c8cb327e33f9c30e2cd4b4a134d3fb
Contains already code starting the migration

**Comment by BT-aestebanez** [comment]
@manuelcalerosolis What you can do is to rename this branch in your local environment:
xtendoo-corporation:15.0-mig-commission -> xtendoo-corporation:15.0-mig-commission-origin
then create a new branch from 15.0 xtendoo-corporation:15.0-mig-commission
Apply the isort, black etc.
It will include some commits.
Then copy/paste the code from xtendoo-corporation:15.0-mig-commission-origin to the new xtendoo-corporation:15.0-mig-commission so you have all your changes in a separate commit.

Do you understand now?

**Pull request closed without merging**
