### PR TITLE
[10.0][IMP] sale_commission: Add line agents filter

### PR DESCRIPTION
**Pull request by SimoRubi**
Adding a filter to find quotations/orders that have at least one line containing the searched agent.

### CODE REVIEW

**Review by tafaRU — CHANGES_REQUESTED** [review]
Please update the module version.

**Comment by SimoRubi** [comment]
> Please update the module version.

@tafaRU thanks for the review, done

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
@mrcast please have a look, thanks

**Review by mrcast — APPROVED** [review]
Functional test ok!

**Pull request merged**
