### PR TITLE
[14.0][ADD]sale_commission_queued: add queue to settlement wizard

### PR DESCRIPTION
**Pull request by toita86**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please remove me from maintainer, as I don't even touch this module.

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM. Could you add me as maintainer as well?

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Review by francesco-ooops — APPROVED** [review]
@pedrobaeza can this be merged? thanks!

**Pull request merged**
