### PR TITLE
[16.0][FIX] account_commission: Regenerate agents button invisibility

### PR DESCRIPTION
**Pull request by jguenat**
- xml states and attrs invisible are combined with AND operator which was not correct in this case, we need OR.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Please remember to include the version in the PR title (only there, not in the commit message).

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please don't mix things in the same PR.

**Comment by jguenat** [comment]
Hello @pedrobaeza 
Is it possible to do a single PR with multiple small fixes in this case?
i can rename the title and it would reduce PR noise?

**Comment by pedrobaeza** [comment]
They are a bit conflicting, as I can agree with one patch, but not with others. I don't agree with the latest ones, and that's why I have raised this concern.

**Comment by jguenat** [comment]
Okay then I'll create separate PRs, also bonus question, is there anything I can do to make codecov/project happy?
How is it possible to have a patch coverage of 100% and projet diminishing?
thanks a lot for your time.

**Comment by pedrobaeza** [comment]
I'm thinking since a bit that Codecov is not being fed with correct data for its analysis, so don't take it very seriously.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
