### PR TITLE
[15.0][MIG] sale_commission_salesman: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
@tecnativa TT37305

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @victoralmau please review

**Review by pedrobaeza — COMMENTED** [review]
Add you to contributors, and please put this icon:

icon
icon

Add also a ROADMAP.rst file saying that `- This module can be split into 2: account_commission_salesman and sale_commission_salesman.`.

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza done, please review

**Review by pedrobaeza — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]
Code review OK

**Comment by pedrobaeza** [comment]
This one shouldn't be renamed, as it depends on `sale`. I'm removing it from the repository to do again the PR.

**Pull request merged**
