### PR TITLE
[MIG] sale_commission_delegated_partner: Migration to 14.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration 
Depends on #356

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Comment by francesco-ooops** [comment]
@etobella would it be possible to add a usage and/or configuration file to this module?

thanks!

**Comment by etobella** [comment]
Sure!! Let me ask my team 

@sanchonuria @kluna1998

**Pull request merged**
