### PR TITLE
[ADD] MV sale commission formula to updated module

### PR DESCRIPTION
**Pull request by hurrinico**
In order to fix https://github.com/OCA/commission/pull/23 i create this PR

### CODE REVIEW

**Comment by eLBati** [comment]
Thanks @hurrinico , please fix tests

**Comment by hurrinico** [comment]
@eLBati travis is green

**Comment by dcorio** [comment]
it's :+1: by me
tested and confirmed working

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
