### PR TITLE
[11.0][IMP] sale_commission: Total revamp

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Remove onchange hackings as they are not needed with new JS views.
* Extract common code between sales orders and invoices, creating 2 mixins.
* Adapt tests.
* Improve README with detailed explanations.
* README by fragments.
* Changed `settled` condition to a more suitable one, moving the condition to _skip_settlement.
* Improve interface for not removing editable option in lines: you have a new icon that popups a window with agents. This icon is available according certain conditions. Check README for more details.
* Add constraint for avoiding the modification of a settled commission.
* Add agent values when no other value is provided. This way, we add compatibility with modules like `sale_product_set` or `sale_order_variant_mgmt`.

From #175, I have integrated the BI analysis + report, adapted to these changes.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@aitorbouzas please check this one that integrates the idea of popup window we talked about in v12, but for v11, with tons of more things. I haven't been able to preserve your authorship in the commit, as it's everything mixed. Anyhow, I have preserved the commit for your other contribution, the BI analysis + report.

@eLBati please review this one, with a very improved flow for commissions, and without any apparent problem that requires hacks.

**Comment by pedrobaeza** [comment]
@eLBati can you please validate these changes?

**Review by eLBati — APPROVED** [review]
@pedrobaeza thanks

**Comment by pedrobaeza** [comment]
Thanks! I'm going to proceed to merge for moving this to v12.

**Pull request merged**
